image: debian/buster
environment:
  CI_REGISTRY: docker.io
  CI_REGISTRY_USER: fourstepper
  CI_REGISTRY_IMAGE: index.docker.io/fourstepper/docker-soju
secrets:
  - 9c21e186-72c5-4633-b9da-5ca7faa0342a
packages:
  - sudo
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
tasks:
  - docker-setup: |
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install docker-ce docker-ce-cli containerd.io
      sudo systemctl start docker
  - docker-login: |
      sudo docker login -u fourstepper --password-stdin=true < ~/.secrets/ci_registry_password
  - docker-build: |
      cd docker-soju
      sudo docker build -t "$CI_REGISTRY_IMAGE" .
  - verify: |
      sudo docker run  -e USER='admin' -e PASSWORD='password' \
      -e LISTEN_METHOD='irc+insecure' -e LISTEN_HOST='localhost' \
      -e LISTEN_PORT='6667' -p 6667:6667 "$CI_REGISTRY_IMAGE"
  - docker-push: |
      sudo docker push "$CI_REGISTRY_IMAGE"
